package cq.air.condition.installers;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.text.BadLocationException;

/**
 *
 *@author Mohit Redhu
 *#Student ID: S12100962
 */
public class InputInstallationData extends FrameLayout {
 
    DefaultComboBoxModel dml = new DefaultComboBoxModel();
    /**
     * Creates new form InputInstallationData
     * @param tech
     * @param ins
     */
    public InputInstallationData(List<TechnicianDetails> tech, List<InstallationDetails> ins) {
        
        techList = tech;
        insList = ins;
        
        techList.forEach(technician->{
        dml.addElement(technician.getName());
        });
            
        initComponents();
        
        zoneButtonGroup.add(jRadioButton1);
        zoneButtonGroup.add(jRadioButton2);
        zoneButtonGroup.add(jRadioButton3);
        zoneButtonGroup.add(jRadioButton4);
        zoneButtonGroup.add(jRadioButton5);
        
        outletButtonGroup.add(jRadioButton01);
        outletButtonGroup.add(jRadioButton02);
        outletButtonGroup.add(jRadioButton03);
        outletButtonGroup.add(jRadioButton04);
        outletButtonGroup.add(jRadioButton05);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outletButtonGroup = new javax.swing.ButtonGroup();
        zoneButtonGroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        hpComboBox = new javax.swing.JComboBox<>();
        hpLabel = new javax.swing.JLabel();
        zoneLabel = new javax.swing.JLabel();
        outletLabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton04 = new javax.swing.JRadioButton();
        jRadioButton03 = new javax.swing.JRadioButton();
        jRadioButton02 = new javax.swing.JRadioButton();
        jRadioButton01 = new javax.swing.JRadioButton();
        jRadioButton05 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        startLabel = new javax.swing.JLabel();
        endLabel = new javax.swing.JLabel();
        technicianLabel = new javax.swing.JLabel();
        technicianComboBox = new javax.swing.JComboBox<>();
        startFormattedTextField = new javax.swing.JFormattedTextField();
        endFormattedTextField = new javax.swing.JFormattedTextField();
        installSubmitButton = new javax.swing.JButton();
        clearButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter Installation Details");
        setLocation(new java.awt.Point(500, 100));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Building Details"));

        addressLabel.setText("Address:");

        hpComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 HP", "1.5 HP", "2 HP", "2.5 HP", "3 HP" }));

        hpLabel.setText("HP:");

        zoneLabel.setText("Number of Zones:");

        outletLabel.setText("Number of Outlets:");

        jRadioButton1.setText("1");
        jRadioButton1.setActionCommand("1");

        jRadioButton2.setText("2");
        jRadioButton2.setActionCommand("2");

        jRadioButton3.setText("3");
        jRadioButton3.setActionCommand("3");

        jRadioButton4.setText("4");
        jRadioButton4.setActionCommand("4");

        jRadioButton5.setText("5");
        jRadioButton5.setActionCommand("5");

        jRadioButton04.setText("4");
        jRadioButton04.setActionCommand("4");

        jRadioButton03.setText("3");
        jRadioButton03.setActionCommand("3");

        jRadioButton02.setText("2");
        jRadioButton02.setActionCommand("2");

        jRadioButton01.setText("1");
        jRadioButton01.setActionCommand("1");

        jRadioButton05.setText("5");
        jRadioButton05.setActionCommand("5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hpLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(zoneLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(outletLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(hpComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jRadioButton1)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButton2)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButton3)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButton4)
                            .addGap(18, 18, 18)
                            .addComponent(jRadioButton5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton01)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton02)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton03)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton04)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton05)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hpComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hpLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zoneLabel)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton01)
                        .addComponent(jRadioButton02)
                        .addComponent(jRadioButton03)
                        .addComponent(jRadioButton04)
                        .addComponent(jRadioButton05))
                    .addComponent(outletLabel))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Installation Details"));

        startLabel.setText("Start Date:");

        endLabel.setText("End Date:");

        technicianLabel.setText("Technician Name:");

        technicianComboBox.setModel(dml);
        technicianComboBox.setSelectedIndex(technicianComboBox.getSelectedIndex());
        technicianComboBox.setSelectedItem(technicianComboBox);

        startFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        startFormattedTextField.setText("Enter Date in dd/mm/yyyy");
        startFormattedTextField.setToolTipText("Enter Date in dd/mm/yyyy");
        startFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                startFormattedTextFieldFocusGained(evt);
            }
        });

        endFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        endFormattedTextField.setText("Enter Date in dd/mm/yyyy");
        endFormattedTextField.setToolTipText("Enter Date in dd/mm/yyyy");
        endFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                endFormattedTextFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(technicianLabel)
                    .addComponent(endLabel)
                    .addComponent(startLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(technicianComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startFormattedTextField)
                    .addComponent(endFormattedTextField))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startLabel)
                    .addComponent(startFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endLabel)
                    .addComponent(endFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(technicianLabel)
                    .addComponent(technicianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        installSubmitButton.setText("Submit");
        installSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installSubmitButtonActionPerformed(evt);
            }
        });

        clearButton2.setText("Clear");
        clearButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clearButton2)
                        .addGap(125, 125, 125)
                        .addComponent(installSubmitButton)
                        .addGap(0, 218, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(installSubmitButton)
                    .addComponent(clearButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new MainFrame(techList, insList).setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void startFormattedTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_startFormattedTextFieldFocusGained
        if(startFormattedTextField.getText().compareToIgnoreCase("Enter Date in dd/mm/yyyy") == 0)
            startFormattedTextField.setText("");
    }//GEN-LAST:event_startFormattedTextFieldFocusGained

    private void endFormattedTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_endFormattedTextFieldFocusGained
        if(endFormattedTextField.getText().compareToIgnoreCase("Enter Date in dd/mm/yyyy") == 0)    
            endFormattedTextField.setText("");
    }//GEN-LAST:event_endFormattedTextFieldFocusGained

    private void installSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installSubmitButtonActionPerformed
        if(addressTextField.getText().isBlank() 
                || zoneButtonGroup.getSelection() == null
                || outletButtonGroup.getSelection() == null
                || startFormattedTextField.getText().compareToIgnoreCase("Enter Date in dd/mm/yyyy")==0
                || endFormattedTextField.getText().compareToIgnoreCase("Enter date in dd/mm/yyyy")==0)
        {
            errorMessage("Please enter the details in all the fields!!");
        }
        else if(addressTextField.getText().matches("-?\\d+"))
            errorMessage("Insert a valid address!");
        else try {
            if((Integer.parseInt(endFormattedTextField.getText(6,4))-Integer.parseInt(startFormattedTextField.getText(6,4))) <= 0)
            {
                if((Integer.parseInt(endFormattedTextField.getText(3,2))-Integer.parseInt(startFormattedTextField.getText(3,2))) <= 0)
                {
                    if((Integer.parseInt(endFormattedTextField.getText(0,2))-Integer.parseInt(startFormattedTextField.getText(0,2))) < 1)
                        errorMessage("End Date should at least be one day after Start Date!");
                    else
                    {
                        insList.add(new InstallationDetails(addressTextField.getText(),
                            hpComboBox.getItemAt(hpComboBox.getSelectedIndex()),
                            zoneButtonGroup.getSelection().getActionCommand(),
                            outletButtonGroup.getSelection().getActionCommand(),
                            startFormattedTextField.getText(),
                            endFormattedTextField.getText(),
                            technicianComboBox.getItemAt(technicianComboBox.getSelectedIndex())));
                        this.setVisible(false);
                    }
                }
                else if((Integer.parseInt(endFormattedTextField.getText(6,4))-Integer.parseInt(startFormattedTextField.getText(6,4))) < 0)
                    errorMessage("End Date should at least be one day after Start Date!");
                else
                {
                    insList.add(new InstallationDetails(addressTextField.getText(),
                        hpComboBox.getItemAt(hpComboBox.getSelectedIndex()),
                        zoneButtonGroup.getSelection().getActionCommand(),
                        outletButtonGroup.getSelection().getActionCommand(),
                        startFormattedTextField.getText(),
                        endFormattedTextField.getText(),
                        technicianComboBox.getItemAt(technicianComboBox.getSelectedIndex())));
                    this.setVisible(false);
                }
            }
            else
            {
                insList.add(new InstallationDetails(addressTextField.getText(),
                    hpComboBox.getItemAt(hpComboBox.getSelectedIndex()),
                    zoneButtonGroup.getSelection().getActionCommand(),
                    outletButtonGroup.getSelection().getActionCommand(),
                    startFormattedTextField.getText(),
                    endFormattedTextField.getText(),
                    technicianComboBox.getItemAt(technicianComboBox.getSelectedIndex())));
                this.setVisible(false);
            }
        } catch (BadLocationException ex) {
            Logger.getLogger(InputInstallationData.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(!this.isVisible())
            new MainFrame(techList, insList).setVisible(true);
    }//GEN-LAST:event_installSubmitButtonActionPerformed

    private void clearButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton2ActionPerformed
        addressTextField.setText("");
        hpComboBox.setSelectedIndex(0);
        zoneButtonGroup.clearSelection();
        outletButtonGroup.clearSelection();
        startFormattedTextField.setText("Enter date in dd/mm/yyyy");
        endFormattedTextField.setText("Enter date in dd/mm/yyyy");
        technicianComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_clearButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputInstallationData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputInstallationData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputInstallationData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputInstallationData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton clearButton2;
    private javax.swing.JFormattedTextField endFormattedTextField;
    private javax.swing.JLabel endLabel;
    private javax.swing.JComboBox<String> hpComboBox;
    private javax.swing.JLabel hpLabel;
    private javax.swing.JButton installSubmitButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton01;
    private javax.swing.JRadioButton jRadioButton02;
    private javax.swing.JRadioButton jRadioButton03;
    private javax.swing.JRadioButton jRadioButton04;
    private javax.swing.JRadioButton jRadioButton05;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.ButtonGroup outletButtonGroup;
    private javax.swing.JLabel outletLabel;
    private javax.swing.JFormattedTextField startFormattedTextField;
    private javax.swing.JLabel startLabel;
    private javax.swing.JComboBox<String> technicianComboBox;
    private javax.swing.JLabel technicianLabel;
    private javax.swing.ButtonGroup zoneButtonGroup;
    private javax.swing.JLabel zoneLabel;
    // End of variables declaration//GEN-END:variables
}
